/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#fffaf0",
        foreground: "#0a0a0a",
        primary: "#0a0a0a",
        "primary-foreground": "#fffaf0",
        ink: "#0a0a0a",
        canvas: "#fffaf0",
        "gigs-pink": "#ff4d8b",
        "gigs-purple": "#b8a4ed",
        "gigs-orange": "#ffb084",
        "gigs-yellow": "#e8b94a",
        "gigs-teal": "#a4d4c5",
        "gigs-dark": "#1a3a3a",
        "gigs-coral": "#ff6b5a",
        success: "#22c55e",
        warning: "#f59e0b",
        error: "#ef4444",
      },
      fontFamily: {
        display: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        sans: ["Inter", "sans-serif"],
      },
      fontSize: {
        "display-hero": ["clamp(3.5rem, 9vw, 11rem)", { lineHeight: "0.82", letterSpacing: "-0.05em", fontWeight: "900" }],
        "display-xl": ["72px", { lineHeight: "0.95", letterSpacing: "-0.04em", fontWeight: "900" }],
        "display-lg": ["56px", { lineHeight: "1", letterSpacing: "-0.03em", fontWeight: "900" }],
        "display-md": ["44px", { lineHeight: "1.05", letterSpacing: "-0.03em", fontWeight: "900" }],
        "display-sm": ["32px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "900" }],
        "title-lg": ["24px", { lineHeight: "1.15", letterSpacing: "-0.01em", fontWeight: "900" }],
        "title-md": ["18px", { lineHeight: "1.3", letterSpacing: "0", fontWeight: "800" }],
        "title-sm": ["16px", { lineHeight: "1.4", letterSpacing: "0", fontWeight: "800" }],
        "body-md": ["16px", { lineHeight: "1.55", letterSpacing: "0", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "1.55", letterSpacing: "0", fontWeight: "400" }],
        caption: ["13px", { lineHeight: "1.4", letterSpacing: "0", fontWeight: "800" }],
        "caption-uppercase": ["12px", { lineHeight: "1.4", letterSpacing: "0.12em", fontWeight: "800" }],
        button: ["14px", { lineHeight: "1", letterSpacing: "0", fontWeight: "800" }],
        "nav-link": ["16px", { lineHeight: "1.4", letterSpacing: "0", fontWeight: "700" }],
      },
      borderRadius: {
        xs: "0px",
        sm: "2px",
        md: "4px",
        lg: "8px",
        xl: "12px",
        pill: "9999px",
        full: "9999px",
      },
      boxShadow: {
        brut: "6px 6px 0 0 #0a0a0a",
        "brut-sm": "4px 4px 0 0 #0a0a0a",
        "brut-lg": "10px 10px 0 0 #0a0a0a",
      },
      spacing: {
        xxs: "4px",
        xs: "8px",
        sm: "12px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        xxl: "48px",
        section: "96px",
      },
    },
  },
  plugins: [],
}