const QUEUE_BATCH_SIZE = parseInt(process.env.QUEUE_BATCH_SIZE, 10) || 50;
const QUEUE_DEQUEUE_INTERVAL_MS =
  parseInt(process.env.QUEUE_DEQUEUE_INTERVAL_MS, 10) || 5000;
const QUEUE_STREAM_POLL_INTERVAL_MS =
  parseInt(process.env.QUEUE_STREAM_POLL_INTERVAL_MS, 10) || 2000;
const QUEUE_STREAM_HEARTBEAT_MS =
  parseInt(process.env.QUEUE_STREAM_HEARTBEAT_MS, 10) || 15000;
const QUEUE_SEQ_KEY = "queue:seq";
const GRANTED_TTL_SECONDS = parseInt(process.env.GRANTED_TTL_SECONDS, 10) || 300;
const LOCK_TTL_SECONDS = parseInt(process.env.LOCK_TTL_SECONDS, 10) || 300;
const PLATFORM_COMMISSION_PERCENT =
  parseInt(process.env.PLATFORM_COMMISSION_PERCENT, 10) || 10;

module.exports = {
  QUEUE_BATCH_SIZE,
  QUEUE_DEQUEUE_INTERVAL_MS,
  QUEUE_STREAM_POLL_INTERVAL_MS,
  QUEUE_STREAM_HEARTBEAT_MS,
  QUEUE_SEQ_KEY,
  GRANTED_TTL_SECONDS,
  LOCK_TTL_SECONDS,
  PLATFORM_COMMISSION_PERCENT,
};
